### ISSUE TITLE
Linux aarch64 build on Ubuntu 20.04 - error ::abort() has not been declared

### ISSUE THREAD

**Issue by romadu** [deathkiller/jazz2-native#11]
When trying to compile on Ubuntu 20.04 for aarch64 I get this error
`/Jazz2-native/Jazz2/nCine/Base/../../Common.h:101:22: error: '::abort' has not been declared`

Any thoughts?

**Comment by deathkiller** [comment]
You can try to change this line - https://github.com/deathkiller/jazz2-native/blob/master/Jazz2/Common.h#L101 - to `#define BREAK() std::abort()`.
If it still doesn't work, try to change this line - https://github.com/deathkiller/jazz2-native/blob/master/Jazz2/Common.h#L91 - to `#if 0`.

**Comment by deathkiller** [comment]
This is strange, do you have the latest version of the compiler? Can you use some different compiler? GCC or Clang?

**Comment by romadu** [comment]
I compiled and installed newer gcc 9.3 and have the same errors. I guess there's something incompatible in my aarch64 ubuntu environment.

**Comment by deathkiller** [comment]
I found the same errors in GitHub Actions and fixed them, so it will probably work for you too.

**Comment by romadu** [comment]
Thanks. Now I have this error when running Gcc SDL
```Make Error at cmake/ncine_imported_targets.cmake:10 (FetchContent_MakeAvailable):
  Unknown CMake command "FetchContent_MakeAvailable"```

**Comment by deathkiller** [comment]
Your CMake installation is probably missing some modules, but you found `-D NCINE_DOWNLOAD_DEPENDENCIES=OFF`, so that's ok for now.

One solution probably could be to install all packages, because system packages has higher priority that `Libs` directory:
```
apt-get install libgl1-mesa-dev libglew-dev libglfw3-dev libsdl2-dev libopenal-dev libopenmpt-dev zlib1g-dev
```

The second solution is to fix headers in `Libs` directory by hand according to your error message.

**Comment by romadu** [comment]
Thanks very much for your help! I have it working now!! I had to go through glew.h and copy typedef entries from the top of the file down for the GLEW_FUN_EXPORT variables used by jazz2. Not sure why, but doing that worked.

For example: 
```typedef void (GLAPIENTRY * PFNGLGETPATHTEXGENFVNVPROC) (GLenum texCoordSet, GLenum pname, GLfloat* value);
GLEW_FUN_EXPORT PFNGLGETPATHTEXGENFVNVPROC __glewGetPathTexGenfvNV;
typedef void (GLAPIENTRY * PFNGLGETPATHTEXGENIVNVPROC) (GLenum texCoordSet, GLenum pname, GLint* value);
GLEW_FUN_EXPORT PFNGLGETPATHTEXGENIVNVPROC __glewGetPathTexGenivNV;
```

**Comment by deathkiller** [comment]
Great. Can you search for the same file (`glew.h`) in your system directories? And tell me where is located, and maybe compare it with the file in `Libs` directory?
